name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run pwd
        run: pwd

      - name: Run touch
        run: touch test.txt

      - name: Run ls -al
        run: ls -al

  test:
    runs-on: ubuntu-latest
    name: 테스트
    steps:
      - name: Run ls -al
        run: ls -al

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run ls -al
        run: ls -al

      - name: Run node -v
        run: node -v

      - name: Run script
        run: npm test

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: node -v

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: node -v

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          check-latest: true
      - run: node -v

  custom_action_test_job:
    runs-on: ubuntu-latest
    name: say hello world
    steps:
      - name: Run Custom Actions
        id: hello
        uses: luke-hanwook/hello-world-docker-action@master
        with:
          who-to-greet: "Mona the Octocat"
